### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by LuisHsu** [AndrewZZJ/Food-chain-frontend#3]
elements from the upper component:
- [x] width: the width of the tile image.
- [x] height: the height of the tile image.

things can be generated:
- [x] src: the URL of the tile image.

**Comment by a23971860** [comment]
elements from upper component:

 

- [ ] width: the width of the tile image.

 

- [ ] height: the height of the tile image.

things can be generated:

 

- [ ] src: the url of the tile image.
